export const capabilities = {
  version: "0.3.1",
  access: "thread-management-with-permission-approvals",
  scope: { projects: "all including Personal", threads: "all projects including hidden; caller-controlled pagination", hostsAndProviders: "read-only discovery" },
  pluginLimits: null,
  included: [
    "Create, fork, handoff, send/steer, stop and retry threads.",
    "Rename, set parent/section/visibility, pin/reorder, mark read/unread, archive/unarchive.",
    "Read full conversations, results, changes, queued work and pending interactions; wait for native progress.",
    "Edit, reorder, cancel or explicitly send queued messages; stale edits require the listed updatedAt.",
    "Answer pending provider questions and native/plugin forms.",
    "Approve or deny a specific pending permission request, including allow-for-session when offered by BB.",
    "Optional durable idempotency receipts for dispatch and interaction responses.",
  ],
  excluded: [
    "General SDK dispatch, CLI execution and arbitrary plugin RPC.",
    "Permanent thread/project/section deletion.",
    "Direct filesystem and terminal access, attachment administration.",
    "Git/PR writes, publishing/sharing, BB settings, plugins, providers and machine administration.",
  ],
  nativeBoundaries: [
    "Thread agents can execute code and change files under their own permissions. Narrowing management tools is not an execution sandbox.",
    "BB/provider/host validation, native concurrency policy, usage costs, retained-history truncation, pagination and client/proxy timeouts still apply.",
    "Permission decisions are bound to a pending interaction and its availableDecisions. There is no global machine permission-setting tool.",
    "threads.update supports model/reasoning but not standalone permissionMode/serviceTier; pass those with create/send. Fork requires provider session-clone support.",
    "Before a scheduled thread's first run, follow-ups must explicitly pass the creation model on BB 0.42.1 (no stored execution model yet).",
    "Archive can cascade to child threads and trigger native managed-workspace cleanup; thread history is retained.",
    "Question/form answers must match the pending request's native schema. No arbitrary plugin RPC is exposed.",
    "Waits need an active caller; there are no automatic completion callbacks to disconnected clients.",
    "Idempotency receipts cannot be atomic with BB commits. Lost responses remain outcome_unknown and must not be blindly redispatched.",
  ],
  legacySettings: "Former project/host/provider scopes, permission ceiling and quotas remain retired and ignored. Existing settings, credentials and operation history are preserved.",
} as const;
