// Generated by scripts/generate-sdk-api.mjs from @get-bb/plugin-sdk 0.4.87.
// Do not edit by hand: run `npm run sdk-api` after `bb plugin types`.
export const SDK_VERSION = "0.4.87";

// Every SDK method the sandbox exposes, one declaration per line. SDK_PATHS
// in codemode.ts is derived from it and the tool descriptions embed it.
export const SDK_METHODS = `
experimental_desktopBrowsers.listInstances(input: ExperimentalDesktopBrowserHostRequest): Promise<ExperimentalDesktopBrowserInstances>;
experimental_desktopBrowsers.listTabs(input: ExperimentalDesktopBrowserScope): Promise<ExperimentalDesktopBrowserTabs>;
experimental_desktopBrowsers.createTab(input: ExperimentalDesktopBrowserCreateInput): Promise<ExperimentalDesktopBrowserCreated>;
experimental_desktopBrowsers.acquireControl(input: ExperimentalDesktopBrowserAcquireInput): Promise<ExperimentalDesktopBrowserLease>;
experimental_desktopBrowsers.openConnection(input: ExperimentalDesktopBrowserLeaseRequest): Promise<ExperimentalDesktopBrowserConnection>;
experimental_desktopBrowsers.releaseControl(input: ExperimentalDesktopBrowserLeaseRequest): Promise<{ ok: true }>;
experimental_desktopBrowsers.revealTab(input: ExperimentalDesktopBrowserTabRequest): Promise<{ ok: true }>;
experimental_desktopBrowsers.closeTab(input: ExperimentalDesktopBrowserTabRequest): Promise<{ ok: true }>;
experimental_desktopBrowsers.captureTab(input: ExperimentalDesktopBrowserTabRequest): Promise<ExperimentalDesktopBrowserCapture>;
experimental_desktopBrowsers.listImportSources(input: ExperimentalDesktopBrowserInstanceRequest): Promise<ExperimentalDesktopBrowserImportSources>;
experimental_desktopBrowsers.importCookies(input: ExperimentalDesktopBrowserImportCookiesInput): Promise<ExperimentalDesktopBrowserImportOutcome>;
environments.archiveThreads(args: EnvironmentActionArgs): Promise<EnvironmentArchiveThreadsResult>;
environments.commit(args: EnvironmentCommitArgs): Promise<EnvironmentCommitResult>;
environments.diff(args: EnvironmentDiffArgs): Promise<EnvironmentDiffResult>;
environments.diffBranches(args: EnvironmentDiffBranchesArgs): Promise<EnvironmentDiffBranchesResult>;
environments.diffFile(args: EnvironmentDiffFileArgs): Promise<EnvironmentDiffFileResult>;
environments.diffFiles(args: EnvironmentDiffArgs): Promise<EnvironmentDiffFilesResult>;
environments.diffPatch(args: EnvironmentDiffPatchArgs): Promise<EnvironmentDiffPatchResult>;
environments.get(args: EnvironmentGetArgs): Promise<EnvironmentGetResult>;
environments.list(args?: EnvironmentListArgs): Promise<EnvironmentListResult>;
environments.listProviders(args?: EnvironmentListProvidersArgs): Promise<EnvironmentListProvidersResult>;
environments.delete(args: EnvironmentDeleteArgs): Promise<EnvironmentDeleteResult>;
environments.pullRequest(args: EnvironmentGetArgs): Promise<EnvironmentPullRequestResult>;
environments.markPullRequestDraft(args: EnvironmentActionArgs): Promise<EnvironmentMarkPullRequestDraftResult>;
environments.markPullRequestReady(args: EnvironmentActionArgs): Promise<EnvironmentMarkPullRequestReadyResult>;
environments.mergePullRequest(args: EnvironmentPullRequestMergeArgs): Promise<EnvironmentMergePullRequestResult>;
environments.paths(args: EnvironmentPathsArgs): Promise<EnvironmentPathsResult>;
environments.status(args: EnvironmentStatusArgs): Promise<EnvironmentStatusResult>;
environments.update(args: EnvironmentUpdateArgs): Promise<EnvironmentUpdateResult>;
files.read(args: FileReadArgs): Promise<FileReadResult>;
files.write(args: FileWriteArgs): Promise<FileWriteResult>;
files.list(args: FileListArgs): Promise<FileListResult>;
files.listPaths(args: PathListArgs): Promise<PathListResult>;
files.mkdir(args: FileMkdirArgs): Promise<FileMkdirResult>;
files.move(args: FileMoveArgs): Promise<FileMoveResult>;
files.remove(args: FileRemoveArgs): Promise<FileRemoveResult>;
files.createPreview(args: FilePreviewArgs): Promise<FilePreviewResult>;
hosts.experimental_create(args: MachineCreateArgs): Promise<Host>;
hosts.experimental_getEnrollmentCommand(args: HostGetArgs): Promise<HostEnrollmentCommandResult>;
hosts.createJoinCode(): Promise<HostCreateJoinCodeResult>;
hosts.delete(args: HostDeleteArgs): Promise<HostDeleteResult>;
hosts.directory(args: HostDirectoryArgs): Promise<HostDirectoryResult>;
hosts.get(args: HostGetArgs): Promise<HostGetResult>;
hosts.cloneDefaultPath(args: HostCloneDefaultPathArgs): Promise<HostCloneDefaultPathResult>;
hosts.installProviderCli(args: HostProviderCliInstallArgs): Promise<HostProviderCliInstallResult>;
hosts.list(args?: HostListArgs): Promise<HostListResult>;
hosts.experimental_listProviders(args?: MachineProviderListArgs): Promise<MachineProviderListResult>;
hosts.pathsExist(args: HostPathsExistArgs): Promise<HostPathsExistResult>;
hosts.pickFolder(args: HostPickFolderArgs): Promise<HostPickFolderResult>;
hosts.providerCliStatus(args: HostGetArgs): Promise<HostProviderCliStatusResult>;
hosts.experimental_resume(args: HostActionArgs): Promise<Host>;
hosts.experimental_retryCleanup(args: HostActionArgs): Promise<HostActionResult>;
hosts.retryUpdate(args: HostRetryUpdateArgs): Promise<HostRetryUpdateResult>;
hosts.experimental_suspend(args: HostActionArgs): Promise<Host>;
hosts.update(args: HostUpdateArgs): Promise<HostUpdateResult>;
projects.attachments.copy(args: ProjectAttachmentCopyArgs): Promise<void>;
projects.attachments.read(args: ProjectAttachmentReadArgs): Promise<ProjectAttachmentReadResult>;
projects.attachments.upload(args: ProjectAttachmentUploadArgs): Promise<ProjectAttachmentUploadResult>;
projects.sources.add(args: ProjectSourceAddArgs): Promise<ProjectSourceAddResult>;
projects.sources.delete(args: ProjectSourceDeleteArgs): Promise<ProjectSourceDeleteResult>;
projects.sources.update(args: ProjectSourceUpdateArgs): Promise<ProjectSourceUpdateResult>;
projects.branches(args: ProjectBranchesArgs): Promise<ProjectBranchesResult>;
projects.commands(args: ProjectCommandsArgs): Promise<ProjectCommandsResult>;
projects.create(args: ProjectCreateArgs): Promise<ProjectCreateResult>;
projects.defaultExecutionOptions(args: ProjectDefaultExecutionOptionsArgs): Promise<ProjectDefaultExecutionOptionsResult>;
projects.delete(args: ProjectDeleteArgs): Promise<ProjectDeleteResult>;
projects.fileContent(args: ProjectFileContentArgs): Promise<ProjectFileContentResult>;
projects.files(args: ProjectFilesArgs): Promise<ProjectFilesResult>;
projects.get(args: ProjectGetArgs): Promise<ProjectGetResult>;
projects.list(args?: ProjectListArgs): Promise<ProjectListResult>;
projects.paths(args: ProjectPathsArgs): Promise<ProjectPathsResult>;
projects.promptHistory(args: ProjectPromptHistoryArgs): Promise<ProjectPromptHistoryResult>;
projects.reorder(args: ProjectReorderArgs): Promise<ProjectReorderResult>;
projects.sidebarBootstrap(args?: ProjectSidebarBootstrapArgs): Promise<ProjectSidebarBootstrapResult>;
projects.update(args: ProjectUpdateArgs): Promise<ProjectUpdateResult>;
plugins.catalog.install(args: PluginCatalogInstallArgs): Promise<PluginInstallResult>;
plugins.catalog.installPlan(args: PluginCatalogInstallPlanArgs): Promise<PluginCatalogInstallPlanResult>;
plugins.catalog.search(args: PluginCatalogSearchArgs): Promise<PluginCatalogSearchResult>;
plugins.catalog.status(args?: PluginCatalogStatusArgs): Promise<PluginCatalogStatusResult>;
plugins.marketplaces.add(args: PluginMarketplaceAddArgs): Promise<PluginMarketplaceAddResult>;
plugins.marketplaces.list(args?: PluginMarketplaceListArgs): Promise<PluginMarketplaceListResult>;
plugins.marketplaces.refresh(args?: PluginMarketplaceRefreshArgs): Promise<PluginMarketplaceRefreshResult>;
plugins.marketplaces.remove(args: PluginMarketplaceRemoveArgs): Promise<PluginMarketplaceRemoveResult>;
plugins.applyUpdate(args: PluginIdArgs): Promise<PluginApplyUpdateResult>;
plugins.callRpc(args: PluginRpcArgs<TOutput>): Promise<TOutput>;
plugins.checkUpdates(args?: PluginCheckUpdatesArgs): Promise<PluginCheckUpdatesResult>;
plugins.disable(args: PluginIdArgs): Promise<PluginDisableResult>;
plugins.enable(args: PluginIdArgs): Promise<PluginEnableResult>;
plugins.getSettings(args: PluginGetSettingsArgs): Promise<PluginGetSettingsResult>;
plugins.getSource(args: PluginGetSourceArgs): Promise<PluginGetSourceResult>;
plugins.install(args: PluginInstallArgs): Promise<PluginInstallResult>;
plugins.list(args?: PluginListArgs): Promise<PluginListResult>;
plugins.listUpdateResults(args?: PluginListUpdateResultsArgs): Promise<PluginCheckUpdatesResult>;
plugins.reload(args?: PluginReloadArgs): Promise<PluginReloadResult>;
plugins.remove(args: PluginIdArgs): Promise<PluginRemoveResult>;
plugins.token(args: PluginTokenArgs): Promise<PluginTokenResult>;
plugins.updateSettings(args: PluginSettingsUpdateArgs): Promise<PluginUpdateSettingsResult>;
providers.list(args?: ProviderListArgs): Promise<ProviderListResult>;
providers.models(args?: ProviderModelsArgs): Promise<ProviderModelsResult>;
skills.registry.detail(args: RegistrySkillSourceArgs): Promise<RegistrySkillDetail>;
skills.registry.entries(args: RegistrySkillEntriesArgs): Promise<RegistrySkillEntriesResponse>;
skills.registry.get(args: RegistrySkillIdArgs): Promise<RegistrySkill>;
skills.registry.install(args: RegistrySkillInstallArgs): Promise<RegistrySkillInstallResponse>;
skills.registry.repositoryStars(args: RegistryRepositoryArgs): Promise<RegistryRepositoryStars>;
skills.registry.search(args?: RegistrySkillsSearchArgs): Promise<RegistrySkillsPage>;
skills.getContent(args: SkillContentArgs): Promise<SkillContentResponse>;
skills.list(args: SkillListArgs): Promise<SkillListResponse>;
skills.listFiles(args: SkillIdentityArgs): Promise<SkillFilesResponse>;
skills.remove(args: SkillDeleteArgs): Promise<{ deletedPath: string }>;
skills.update(args: SkillUpdateArgs): Promise<{ filePath: string; revision: string }>;
status.get(args?: StatusGetArgs): Promise<StatusResult>;
system.uiPreferences.list(args?: SystemUiPreferencesArgs): Promise<SystemUiPreferencesResult>;
system.uiPreferences.set(args: SystemUpdateUiPreferenceArgs<Key>): Promise<SystemUiPreferenceResult<Key>>;
system.uiPreferences.reset(args: SystemResetUiPreferenceArgs<Key>): Promise<SystemUiPreferenceResult<Key>>;
system.machineEnvironment(): Promise<MachineEnvironmentList>;
system.replaceMachineEnvironment(input: MachineEnvironmentReplace): Promise<MachineEnvironmentList>;
system.attention(args?: SystemAttentionArgs): Promise<SystemAttentionResult>;
system.config(args?: SystemConfigArgs): Promise<SystemConfigResult>;
system.executionOptions(args?: SystemExecutionOptionsArgs): Promise<SystemExecutionOptionsResult>;
system.cliSkillsStatus(args?: SystemCliSkillsStatusArgs): Promise<SystemCliSkillsStatusResult>;
system.installCliSkills(args: SystemInstallCliSkillsArgs): Promise<SystemInstallCliSkillsResult>;
system.reloadConfig(): Promise<SystemReloadConfigResult>;
system.transcribeVoice(args: SystemVoiceTranscriptionArgs): Promise<SystemVoiceTranscriptionResult>;
system.updateExperiments(args: Experiments): Promise<SystemUpdateExperimentsResult>;
system.updateGeneralSettings(args: AppSettingsUpdate): Promise<SystemUpdateGeneralSettingsResult>;
system.updateKeyboardSettings(args: AppKeybindingOverrides): Promise<SystemUpdateKeyboardSettingsResult>;
system.providerStates(args?: SystemProviderStatesArgs): Promise<SystemProviderStatesResult>;
system.usageLimits(args?: SystemUsageLimitsArgs): Promise<SystemUsageLimitsResult>;
system.version(args?: SystemVersionArgs): Promise<SystemVersionResult>;
terminals.close(args: TerminalCloseArgs): Promise<TerminalCloseResult>;
terminals.create(args: TerminalCreateArgs): Promise<TerminalCreateResult>;
terminals.get(args: TerminalGetArgs): Promise<TerminalGetResult>;
terminals.input(args: TerminalInputArgs): Promise<TerminalInputResult>;
terminals.list(args: TerminalListArgs): Promise<TerminalListResult>;
terminals.output(args: TerminalOutputArgs): Promise<TerminalOutputResult>;
terminals.rename(args: TerminalRenameArgs): Promise<TerminalRenameResult>;
terminals.restart(args: TerminalRestartArgs): Promise<TerminalRestartResult>;
terminals.resize(args: TerminalResizeArgs): Promise<TerminalResizeResult>;
theme.get(args?: ThemeGetArgs): Promise<ThemeGetResult>;
theme.catalog(args?: ThemeCatalogArgs): Promise<ThemeCatalogResult>;
theme.resolve(args: ThemeResolveArgs): Promise<ThemeResolveResult>;
theme.set(selection: ThemeSetInput): Promise<ThemeSetResult>;
theme.set(themeId: string): Promise<ThemeSetResult>;
threadSections.create(args: CreateThreadSectionRequest): Promise<ThreadSectionCreateResult>;
threadSections.delete(args: DeleteThreadSectionRequest): Promise<ThreadSectionDeleteResult>;
threadSections.list(args?: ThreadSectionListArgs): Promise<ThreadSectionListResult>;
threadSections.update(args: UpdateThreadSectionRequest): Promise<ThreadSectionUpdateResult>;
threads.events.list(args: ThreadEventsListArgs): Promise<ThreadEventsListResult>;
threads.events.wait(args: ThreadEventWaitArgs): Promise<ThreadEventWaitResult>;
threads.queue.list(args?: ThreadQueueListArgs): Promise<ThreadQueueListResult>;
threads.interactions.cancel(args: ThreadInteractionTargetArgs): Promise<ThreadInteractionCancelResult>;
threads.interactions.get(args: ThreadInteractionGetArgs): Promise<ThreadInteractionGetResult>;
threads.interactions.list(args: ThreadInteractionListArgs): Promise<ThreadInteractionListResult>;
threads.interactions.resolve(args: ThreadInteractionResolveArgs): Promise<ThreadInteractionResolveResult>;
threads.interactions.respond(args: ThreadInteractionRespondArgs): Promise<ThreadInteractionRespondResult>;
threads.queuedMessages.create(args: ThreadQueuedMessageCreateArgs): Promise<ThreadQueuedMessageCreateResult>;
threads.queuedMessages.delete(args: ThreadQueuedMessageTargetArgs): Promise<ThreadQueuedMessageDeleteResult>;
threads.queuedMessages.list(args: ThreadQueuedMessageArgs): Promise<ThreadQueuedMessagesResult>;
threads.queuedMessages.reorder(args: ThreadQueuedMessageReorderArgs): Promise<ThreadQueuedMessageReorderResult>;
threads.queuedMessages.send(args: ThreadQueuedMessageSendArgs): Promise<ThreadQueuedMessageSendResult>;
threads.queuedMessages.setGroupBoundary(args: ThreadQueuedMessageGroupBoundaryArgs): Promise<ThreadQueuedMessageGroupBoundaryResult>;
threads.queuedMessages.update(args: ThreadQueuedMessageUpdateArgs): Promise<ThreadQueuedMessageUpdateResult>;
threads.tabs.get(args: ThreadStatusArgs): Promise<ThreadTabsResult>;
threads.tabs.update(args: ThreadTabsUpdateArgs): Promise<ThreadTabsUpdateResult>;
threads.archive(args: ThreadActionArgs): Promise<ThreadArchiveResult>;
threads.archiveAll(args: ThreadActionArgs): Promise<ThreadArchiveAllResult>;
threads.childSummary(args: ThreadStatusArgs): Promise<ThreadChildSummaryResult>;
threads.compact(args: ThreadActionArgs): Promise<ThreadCompactResult>;
threads.cancelPlan(args: ThreadActionArgs): Promise<ThreadBannerActionResult>;
threads.clearContext(args: ThreadActionArgs): Promise<ThreadBannerActionResult>;
threads.clearGoal(args: ThreadActionArgs): Promise<ThreadBannerActionResult>;
threads.conversationOutline(args: ThreadStatusArgs): Promise<ThreadConversationOutlineResult>;
threads.count(args?: ThreadCountArgs): Promise<ThreadCountResult>;
threads.defaultExecutionOptions(args: ThreadStatusArgs): Promise<ThreadDefaultExecutionOptionsResult>;
threads.delete(args: ThreadDeleteArgs): Promise<ThreadDeleteResult>;
threads.editMessage(args: ThreadEditMessageArgs): Promise<ThreadEditMessageResult>;
threads.fork(args: ThreadForkArgs): Promise<ThreadForkResult>;
threads.get(args: ThreadGetArgs): Promise<ThreadGetResult>;
threads.getPluginMetadata(args: { threadId: string; pluginId?: string }): Promise<ThreadPluginMetadataResult>;
threads.updatePluginMetadata(args: { threadId: string; pluginId?: string; set?: JsonObject; remove?: string[] }): Promise<ThreadPluginMetadataResult>;
threads.list(args?: ThreadListArgs): Promise<ThreadListResult>;
threads.listRunning(args?: { signal?: AbortSignal }): Promise<ThreadRunningResult>;
threads.markRead(args: ThreadActionArgs): Promise<ThreadReadStateResult>;
threads.markUnread(args: ThreadActionArgs): Promise<ThreadReadStateResult>;
threads.open(args: ThreadOpenArgs): Promise<ThreadOpenResult>;
threads.paneAction(args: ThreadPaneActionArgs): Promise<ThreadPaneActionResult>;
threads.output(args: ThreadOutputArgs): Promise<ThreadOutputResponse>;
threads.pin(args: ThreadActionArgs): Promise<ThreadMutationResult>;
threads.promptHistory(args: ThreadPromptHistoryArgs): Promise<ThreadPromptHistoryResult>;
threads.reorderPinned(args: ThreadPinOrderArgs): Promise<ThreadPinOrderResult>;
threads.resolveMentions(args: ThreadResolveMentionsArgs): Promise<ThreadResolveMentionsResult>;
threads.retry(args: ThreadRetryArgs): Promise<ThreadRetryResult>;
threads.search(args: ThreadSearchArgs): Promise<ThreadSearchResult>;
threads.send(args: ThreadSendArgs): Promise<ThreadSendResult>;
threads.spawn(args: ThreadSpawnArgs): Promise<ThreadSpawnResult>;
threads.stop(args: ThreadActionArgs): Promise<ThreadStopResult>;
threads.context(args: ThreadStatusArgs): Promise<ThreadContextResult>;
threads.timeline(args: ThreadTimelineArgs): Promise<ThreadTimelineResult>;
threads.timelineTurnSummaryDetails(args: ThreadTimelineTurnSummaryDetailsArgs): Promise<ThreadTimelineTurnSummaryDetailsResult>;
threads.storageFiles(args: ThreadStorageFilesArgs): Promise<ThreadStorageFilesResult>;
threads.storageLocation(args: ThreadStatusArgs): Promise<ThreadStorageLocationResult>;
threads.storagePaths(args: ThreadStoragePathsArgs): Promise<ThreadStoragePathsResult>;
threads.unarchive(args: ThreadActionArgs): Promise<ThreadUnarchiveResult>;
threads.unpin(args: ThreadActionArgs): Promise<ThreadMutationResult>;
threads.update(args: ThreadUpdateArgs): Promise<ThreadMutationResult>;
threads.wait(args: ThreadWaitArgs): Promise<ThreadWaitResult>;
guide.render(args?: GuideRenderArgs): GuideRenderResult;`;

// Methods whose args declare `signal?: AbortSignal`. Injecting it anywhere
// else fails strict arg validation.
export const SIGNAL_PATHS: readonly string[] = [
  "environments.diff",
  "environments.diffBranches",
  "environments.diffFile",
  "environments.diffFiles",
  "environments.diffPatch",
  "environments.get",
  "environments.list",
  "environments.listProviders",
  "environments.paths",
  "environments.pullRequest",
  "environments.status",
  "files.createPreview",
  "files.list",
  "files.listPaths",
  "files.read",
  "hosts.cloneDefaultPath",
  "hosts.directory",
  "hosts.experimental_create",
  "hosts.experimental_getEnrollmentCommand",
  "hosts.experimental_listProviders",
  "hosts.get",
  "hosts.list",
  "hosts.pathsExist",
  "hosts.pickFolder",
  "hosts.providerCliStatus",
  "plugins.catalog.installPlan",
  "plugins.catalog.search",
  "plugins.catalog.status",
  "plugins.checkUpdates",
  "plugins.getSettings",
  "plugins.getSource",
  "plugins.list",
  "plugins.listUpdateResults",
  "plugins.marketplaces.list",
  "plugins.marketplaces.refresh",
  "projects.attachments.read",
  "projects.branches",
  "projects.commands",
  "projects.defaultExecutionOptions",
  "projects.fileContent",
  "projects.files",
  "projects.get",
  "projects.list",
  "projects.paths",
  "projects.promptHistory",
  "projects.sidebarBootstrap",
  "providers.list",
  "providers.models",
  "skills.getContent",
  "skills.list",
  "skills.listFiles",
  "skills.registry.detail",
  "skills.registry.entries",
  "skills.registry.get",
  "skills.registry.repositoryStars",
  "skills.registry.search",
  "status.get",
  "system.attention",
  "system.cliSkillsStatus",
  "system.config",
  "system.executionOptions",
  "system.providerStates",
  "system.transcribeVoice",
  "system.uiPreferences.list",
  "system.usageLimits",
  "system.version",
  "terminals.get",
  "terminals.list",
  "terminals.output",
  "theme.catalog",
  "theme.get",
  "theme.resolve",
  "threadSections.list",
  "threads.archive",
  "threads.archiveAll",
  "threads.cancelPlan",
  "threads.childSummary",
  "threads.clearContext",
  "threads.clearGoal",
  "threads.compact",
  "threads.context",
  "threads.conversationOutline",
  "threads.count",
  "threads.defaultExecutionOptions",
  "threads.events.list",
  "threads.events.wait",
  "threads.get",
  "threads.getPluginMetadata",
  "threads.interactions.get",
  "threads.interactions.list",
  "threads.list",
  "threads.listRunning",
  "threads.markRead",
  "threads.markUnread",
  "threads.output",
  "threads.pin",
  "threads.promptHistory",
  "threads.queue.list",
  "threads.queuedMessages.list",
  "threads.resolveMentions",
  "threads.search",
  "threads.stop",
  "threads.storageFiles",
  "threads.storageLocation",
  "threads.storagePaths",
  "threads.tabs.get",
  "threads.timeline",
  "threads.timelineTurnSummaryDetails",
  "threads.unarchive",
  "threads.unpin",
  "threads.updatePluginMetadata",
  "threads.wait"
];
